trigger:
  - master

name: $(TeamProject)_$(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: "APP_NAME"
    value: "docker-webapp-test" # name of the app
  - name: "ACR_NAME"
    value: "dockerwebapptestacr" # name of the Azure Container Registry
  - name: "IMAGE_NAME"
    value: "webapp-test" # name of the Docker Image to create
  - name: "LOCATION"
    value: "uksouth" # where does stuff need deploying?

pool:
  vmImage: "Ubuntu-20.04"

stages:
  - stage: "SetupAzure"
    displayName: "Setup Azure" # friendly name to display in the UI
    jobs:
      - job: "CreateResourceGroup"
        displayName: "Create the Resource Group"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group create --name $(APP_NAME)-rg --location $(LOCATION)
              displayName: "Use Azure CLI to create the Resource Group"
      - job: "SetupCheckAzureContainerRegistry"
        displayName: "Setup / Check the Azure Container Registry"
        dependsOn:
          - "CreateResourceGroup"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr create --resource-group $(APP_NAME)-rg --name $(ACR_NAME) --sku Basic --admin-enabled true
              displayName: "Use Azure CLI to setup / check the Azure Container Registry"

  - stage: "BuildContainer"
    displayName: "Build and Push Conatiner" # friendly name to display in the UI
    jobs:
      - job: "LoginToACR"
        displayName: "Login to the Azure Container Registry"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr login --name $(ACR_NAME)
              displayName: "Use Azure CLI to login to the Azure Container Registry"
      - job: "BuildPushImage"
        displayName: "Build the image"
        dependsOn:
          - "LoginToACR"
        steps:
          - task: Docker@2
            inputs:
              repository: "$(IMAGE_NAME)"
              command: "build"
              Dockerfile: "Dockerfile"
            displayName: "Use Docker task to build the image"
          - task: Docker@2
            inputs:
              repository: "$(IMAGE_NAME)"
              command: "push"
              tags: |
                $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
                $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Date:yyyyMMdd)
            displayName: "Use Docker task to push the image"
