trigger:
  - master

name: $(TeamProject)_$(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: "APP_NAME"
    value: "docker-webapp-test" # name of the app
  - name: "ACR_NAME"
    value: "dockerwebapptestacr" # name of the Azure Container Registry
  - name: "IMAGE_NAME"
    value: "webapp-test" # name of the Docker Image to create
  - name: "LOCATION"
    value: "uksouth" # where does stuff need deploying?

pool:
  vmImage: "Ubuntu-20.04"

stages:
  - stage: "SetupAzure"
    displayName: "Setup Azure" # friendly name to display in the UI
    jobs:
      - job: "CreateResourceGroup"
        displayName: "Create the Resource Group"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group create --name $(APP_NAME)-rg --location $(LOCATION)
              displayName: "Use Azure CLI to create the Resource Group"
      - job: "SetupCheckAzureContainerRegistry"
        displayName: "Setup / Check the Azure Container Registry"
        dependsOn:
          - "CreateResourceGroup"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr create --resource-group $(APP_NAME)-rg --name $(ACR_NAME) --sku Basic --admin-enabled true
              displayName: "Use Azure CLI to setup / check the Azure Container Registry"

  - stage: "BuildContainer"
    displayName: "Build, Tag and Push the conatiner image" # friendly name to display in the UI
    dependsOn:
      - "SetupAzure"
    jobs:
      - job: "BuildPushImage"
        displayName: "Build, tag and push the image"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr login --name $(ACR_NAME) 
                docker image build -t $(IMAGE_NAME) ./
                docker image tag $(IMAGE_NAME) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
                docker image tag $(IMAGE_NAME) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(date '+%Y-%m-%d-%H%M')
                docker image push --all-tags $(ACR_NAME).azurecr.io/$(IMAGE_NAME)
              displayName: "Use Azure CLI to build and push the container image"
