trigger:
  - master

name: $(TeamProject)_$(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: "APP_NAME"
    value: "docker-webapp-test" # name of the app
  - name: "ACR_NAME"
    value: "dockerwebapptestacr" # name of the Azure Container Registry
  - name: "IMAGE_NAME"
    value: "webapp-test" # name of the Docker Image to create
  - name: "LOCATION"
    value: "uksouth" # where does stuff need deploying?

stages:
  - stage: "SetupAzure"
    jobs:
      - job: "Setup Azure"
        pool:
          vmImage: "Ubuntu-latest"
        continueOnError: true
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group create --name $(APP_NAME)-rg --location $(LOCATION)
            displayName: "Setup / check the resource group"
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr create --resource-group $(APP_NAME)-rg --name $(ACR_NAME) --sku Basic --admin-enabled true
            displayName: "Setup / check the Azure Container Registry"

  - stage: "BuildandPushContainerImage"
    jobs:
      - job: "Build Container Image"
        pool:
          vmImage: "Ubuntu-latest"
        continueOnError: true
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr login --name $(ACR_NAME)
            displayName: "Login to the Azure Container Registry"
